---
- name: Run powershell script
  hosts: all
  tasks:
    - name: Run powershell script
      win_shell: |
        $value = Test-Path -Path C:\temp
        if ($value) {
        Remove-Item -Path C:\temp -Force
        }
        New-Item -Path C:\temp -ItemType Directory

    - name: Working .ps file
      win_shell: C:\somescript.ps1 >> C:\somelog.txt
